export const PROFESSION_TITLES = [
  // Home Services
  { value: "cleaner", label: "Cleaner / Housekeeper" },
  { value: "commercial-cleaner", label: "Commercial Cleaner" },
  { value: "plumber", label: "Plumber" },
  { value: "master-plumber", label: "Master Plumber" },
  { value: "electrician", label: "Electrician" },
  { value: "master-electrician", label: "Master Electrician" },
  { value: "painter", label: "Painter" },
  { value: "house-painter", label: "House Painter" },
  { value: "commercial-painter", label: "Commercial Painter" },
  { value: "mover", label: "Mover / Delivery Specialist" },
  { value: "logistics-coordinator", label: "Logistics Coordinator" },
  { value: "gardener", label: "Gardener" },
  { value: "landscaper", label: "Landscaper" },
  { value: "groundskeeper", label: "Groundskeeper" },
  { value: "appliance-repair-tech", label: "Appliance Repair Technician" },
  { value: "handyman", label: "General Handyman" },

  // Events
  { value: "photographer", label: "Photographer" },
  { value: "wedding-photographer", label: "Wedding Photographer" },
  { value: "portrait-photographer", label: "Portrait Photographer" },
  { value: "caterer", label: "Caterer" },
  { value: "chef", label: "Chef / Private Chef" },
  { value: "event-caterer", label: "Event Caterer" },
  { value: "musician", label: "Musician" },
  { value: "dj", label: "DJ" },
  { value: "band-leader", label: "Band Leader" },
  { value: "entertainer", label: "Entertainer / Performer" },
  { value: "event-planner", label: "Event Planner" },
  { value: "wedding-planner", label: "Wedding Planner" },
  {
    value: "corporate-event-coordinator",
    label: "Corporate Event Coordinator",
  },
  { value: "event-decorator", label: "Event Decorator" },
  { value: "floral-designer", label: "Floral Designer" },
  { value: "party-stylist", label: "Party Stylist" },

  // Wellness
  { value: "massage-therapist", label: "Massage Therapist" },
  { value: "spa-therapist", label: "Spa Therapist" },
  { value: "personal-trainer", label: "Personal Trainer" },
  { value: "fitness-coach", label: "Fitness Coach" },
  { value: "gym-instructor", label: "Gym Instructor" },
  { value: "beauty-therapist", label: "Beauty Therapist" },
  { value: "hair-stylist", label: "Hair Stylist" },
  { value: "makeup-artist", label: "Makeup Artist" },
  { value: "nail-technician", label: "Nail Technician" },
  { value: "counselor", label: "Counselor" },
  { value: "therapist", label: "Therapist" },
  { value: "life-coach", label: "Life Coach" },
  { value: "mental-health-counselor", label: "Mental Health Counselor" },

  // Tech
  { value: "web-developer", label: "Web Developer" },
  { value: "frontend-developer", label: "Frontend Developer" },
  { value: "backend-developer", label: "Backend Developer" },
  { value: "full-stack-developer", label: "Full Stack Developer" },
  { value: "device-repair-tech", label: "Device Repair Technician" },
  { value: "phone-repair-specialist", label: "Phone Repair Specialist" },
  { value: "computer-technician", label: "Computer Technician" },
  { value: "it-support-specialist", label: "IT Support Specialist" },
  { value: "help-desk-technician", label: "Help Desk Technician" },
  { value: "systems-administrator", label: "Systems Administrator" },
  { value: "mobile-app-developer", label: "Mobile App Developer" },
  { value: "ios-developer", label: "iOS Developer" },
  { value: "android-developer", label: "Android Developer" },

  // Creative
  { value: "graphic-designer", label: "Graphic Designer" },
  { value: "brand-designer", label: "Brand Designer" },
  { value: "visual-designer", label: "Visual Designer" },
  { value: "video-editor", label: "Video Editor" },
  { value: "videographer", label: "Videographer" },
  { value: "motion-graphics-designer", label: "Motion Graphics Designer" },
  { value: "content-writer", label: "Content Writer" },
  { value: "copywriter", label: "Copywriter" },
  { value: "technical-writer", label: "Technical Writer" },
  { value: "blogger", label: "Blogger" },

  // Lessons
  { value: "academic-tutor", label: "Academic Tutor" },
  { value: "math-tutor", label: "Math Tutor" },
  { value: "science-tutor", label: "Science Tutor" },
  { value: "exam-prep-tutor", label: "Exam Prep Tutor" },
  { value: "music-teacher", label: "Music Teacher" },
  { value: "piano-teacher", label: "Piano Teacher" },
  { value: "guitar-instructor", label: "Guitar Instructor" },
  { value: "language-tutor", label: "Language Tutor" },
  { value: "english-teacher", label: "English Teacher" },
  { value: "esl-instructor", label: "ESL Instructor" },
  { value: "skills-coach", label: "Skills Coach" },
  { value: "career-coach", label: "Career Coach" },
  { value: "business-coach", label: "Business Coach" },

  // Automotive
  { value: "auto-mechanic", label: "Auto Mechanic" },
  { value: "car-mechanic", label: "Car Mechanic" },
  { value: "automotive-technician", label: "Automotive Technician" },
  { value: "car-detailer", label: "Car Detailer" },
  { value: "auto-detailing-specialist", label: "Auto Detailing Specialist" },
  { value: "towing-operator", label: "Towing Service Operator" },
  { value: "recovery-specialist", label: "Recovery Specialist" },
  { value: "auto-parts-supplier", label: "Auto Parts Supplier" },
  { value: "car-parts-specialist", label: "Car Parts Specialist" },

  // Other
  { value: "consultant", label: "Consultant" },
  { value: "business-consultant", label: "Business Consultant" },
  { value: "management-consultant", label: "Management Consultant" },
  { value: "delivery-driver", label: "Delivery Driver" },
  { value: "courier", label: "Courier" },
  { value: "logistics-driver", label: "Logistics Driver" },
  { value: "multi-skilled-professional", label: "Multi-skilled Professional" },
];
